[package]
name = "video-chat-wasm"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = { workspace = true }
web-sys = { workspace = true, features = [
    "console",
    "Window",
    "WorkerGlobalScope",
    "ServiceWorkerGlobalScope",
    "Storage", 
    "Storage"
] }
js-sys = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde-wasm-bindgen = "0.6"
log = { workspace = true }
wasm-logger = { workspace = true }
thiserror = { workspace = true }
video-chat-core = { path = "../core" }
[dev-dependencies]
wasm-bindgen-test = "0.3"
