[package]
name = "video-chat-wasm"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[package.metadata.wasm-pack.profile.release]
wasm-opt = false

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = { workspace = true }
web-sys = { workspace = true, features = [
    "console",
    "Window",
    "WorkerGlobalScope",
    "ServiceWorkerGlobalScope",
    "Storage", 
    "Storage"
] }
js-sys = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde-wasm-bindgen = "0.6"
log = { workspace = true }
wasm-logger = { workspace = true }
thiserror = { workspace = true }
wasm-bindgen-futures = { workspace = true }
video-chat-core = { path = "../core" }
video-chat-media = { path = "../media" }
video-chat-signaling = { path = "../signaling" }
sqlite-wasm-rs = "0.2"
once_cell = "1.19"

[dev-dependencies]
wasm-bindgen-test = "0.3"

[profile.release]
# Optimize for small footprint
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
